import type { GenConfig, ParamRange } from '../types';

/** Split a textarea into trimmed non-empty lines. */
export function splitLines(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}

/** Active (non-"off") params only. */
function activeParams(config: GenConfig): ParamRange[] {
  return config.params.filter((p) => p.kind !== 'off');
}

/** Whether any emoji injection is configured. */
function emojiEnabled(config: GenConfig): boolean {
  return config.emojiEntries.length > 0;
}

/** Resolve an entry's per-slot [min,max] (fixed mode collapses to [v,v]). */
function slot(
  entry: import('../types').EmojiEntry,
  which: 'head' | 'tail' | 'rand',
): [number, number] {
  const min = Math.max(0, Math.floor(entry[`${which}Min`]));
  const max = Math.max(0, Math.floor(entry[`${which}Max`]));
  return entry.mode === 'fixed' ? [min, min] : [Math.min(min, max), Math.max(min, max)];
}

/** Per-flag PowerShell variable name and sidecar JSON key. */
const FLAG_INFO: Record<string, { psVar: string; jsonKey: string; env: string }> = {
  seed: { psVar: 'Seed', jsonKey: 'seed', env: 'TTS_SEED' },
  'num-steps': { psVar: 'NumSteps', jsonKey: 'numSteps', env: 'TTS_NUMSTEPS' },
  'cfg-scale-text': { psVar: 'CfgText', jsonKey: 'cfgScaleText', env: 'TTS_CFGTEXT' },
  'cfg-scale-caption': { psVar: 'CfgCaption', jsonKey: 'cfgScaleCaption', env: 'TTS_CFGCAPTION' },
  'cfg-scale-speaker': { psVar: 'CfgSpeaker', jsonKey: 'cfgScaleSpeaker', env: 'TTS_CFGSPEAKER' },
  'duration-scale': { psVar: 'DurScale', jsonKey: 'durationScale', env: 'TTS_DURSCALE' },
  'sway-coeff': { psVar: 'SwayCoeff', jsonKey: 'swayCoeff', env: 'TTS_SWAYCOEFF' },
  'truncation-factor': { psVar: 'TruncFactor', jsonKey: 'truncationFactor', env: 'TTS_TRUNCFACTOR' },
};

const ALL_JSON_PARAM_KEYS = Object.values(FLAG_INFO).map((i) => i.jsonKey);

// ---------------------------------------------------------------------------
// PowerShell
// ---------------------------------------------------------------------------

/** Escape a string for a PowerShell single-quoted literal. */
function psLit(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** Format a number for embedding as a PowerShell numeric literal (invariant). */
function numLit(p: ParamRange, value: number): string {
  if (p.type === 'int') return String(Math.round(value));
  return value.toFixed(p.decimals);
}

/** PowerShell lines defining $Entries + the Get-Cnt helper (emitted once). */
function psEntriesSetup(config: GenConfig): string[] {
  if (!emojiEnabled(config)) return [];
  const L: string[] = [];
  L.push('function Get-Cnt($a, $b) { $lo = [math]::Min($a, $b); $hi = [math]::Max($a, $b); return (Get-Random -Minimum $lo -Maximum ($hi + 1)) }');
  L.push('$Entries = @(');
  L.push(
    config.emojiEntries
      .map((e) => {
        const [hMin, hMax] = slot(e, 'head');
        const [tMin, tMax] = slot(e, 'tail');
        const [rMin, rMax] = slot(e, 'rand');
        return `  [pscustomobject]@{ Token = ${psLit(e.token)}; HMin = ${hMin}; HMax = ${hMax}; TMin = ${tMin}; TMax = ${tMax}; RMin = ${rMin}; RMax = ${rMax} }`;
      })
      .join(',\n'),
  );
  L.push(')');
  return L;
}

/** PowerShell lines (4-space indented) composing $Text/$Emoji per generation. */
function psEmojiBlock(config: GenConfig): string[] {
  if (!emojiEnabled(config)) {
    return ['    $Emoji = ""', '    $Text = $BaseText'];
  }
  return [
    '    $Head = ""',
    '    $Tail = ""',
    '    $Emoji = ""',
    '    foreach ($en in $Entries) {',
    '      $h = Get-Cnt $en.HMin $en.HMax',
    '      $t = Get-Cnt $en.TMin $en.TMax',
    '      if ($h -gt 0) { $Head += $en.Token * $h; $Emoji += $en.Token * $h }',
    '      if ($t -gt 0) { $Tail += $en.Token * $t; $Emoji += $en.Token * $t }',
    '    }',
    '    $Text = $Head + $BaseText + $Tail',
    '    foreach ($en in $Entries) {',
    '      $r = Get-Cnt $en.RMin $en.RMax',
    '      for ($k = 0; $k -lt $r; $k++) {',
    '        $pos = Get-Random -Minimum 0 -Maximum ($Text.Length + 1)',
    '        $Text = $Text.Substring(0, $pos) + $en.Token + $Text.Substring($pos)',
    '        $Emoji += $en.Token',
    '      }',
    '    }',
  ];
}

export function buildPs1(config: GenConfig): string {
  const active = activeParams(config);
  const texts = splitLines(config.texts);
  const checkpointFlag = config.checkpointKind === 'hf' ? '--hf-checkpoint' : '--checkpoint';

  const L: string[] = [];
  L.push('# Auto-generated by Irodori-TTS Tools. Random-parameter batch generation.');
  L.push('$ErrorActionPreference = "Stop"');
  L.push('chcp 65001 > $null');
  L.push('[Console]::OutputEncoding = [System.Text.Encoding]::UTF8');
  L.push('$inv = [System.Globalization.CultureInfo]::InvariantCulture');
  L.push('');
  L.push(`$OutDir = ${psLit(config.outputDir)}`);
  L.push('New-Item -ItemType Directory -Force -Path $OutDir | Out-Null');
  L.push('');
  L.push('$Texts = @(');
  L.push(texts.map((t) => '  ' + psLit(t)).join(',\n'));
  L.push(')');
  for (const line of psEntriesSetup(config)) L.push(line);
  L.push(`$Model = ${psLit(config.checkpoint)}`);
  if (config.refMode === 'ref-wav') L.push(`$RefWav = ${psLit(config.refWav)}`);
  if (config.caption.trim()) L.push(`$Caption = ${psLit(config.caption)}`);
  L.push('$Index = 0');
  L.push('');
  L.push('foreach ($BaseText in $Texts) {');
  L.push(`  for ($i = 0; $i -lt ${Math.max(1, Math.floor(config.count))}; $i++) {`);
  L.push('    $Index++');

  // Parameter draws.
  for (const p of active) {
    const info = FLAG_INFO[p.flag];
    const v = `$${info.psVar}`;
    if (p.kind === 'fixed') {
      L.push(`    ${v} = ${numLit(p, p.fixed)}`);
    } else if (p.type === 'int') {
      // Get-Random -Maximum is exclusive, so +1 to include max.
      L.push(`    ${v} = Get-Random -Minimum ${Math.round(p.min)} -Maximum ${Math.round(p.max) + 1}`);
    } else {
      L.push(
        `    ${v} = [math]::Round((${p.min.toFixed(p.decimals)} + (Get-Random -Maximum 10001)/10000 * (${p.max.toFixed(p.decimals)} - ${p.min.toFixed(p.decimals)})), ${p.decimals})`,
      );
    }
    if (p.type === 'float') {
      L.push(`    $${info.psVar}Str = ${v}.ToString($inv)`);
    }
  }

  // Emoji + composed text.
  for (const line of psEmojiBlock(config)) L.push(line);

  // Output names.
  const hasSeed = active.some((p) => p.flag === 'seed');
  if (hasSeed) {
    L.push('    $Name = ("{0:D4}_{1}" -f $Index, $Seed)');
  } else {
    L.push('    $Name = ("{0:D4}" -f $Index)');
  }
  L.push('    $Wav = Join-Path $OutDir "$Name.wav"');
  L.push('    $Json = Join-Path $OutDir "$Name.json"');
  L.push('');

  // Build args array.
  L.push('    $cmdArgs = @(');
  L.push(`      ${psLit(checkpointFlag)}, $Model,`);
  L.push('      "--text", $Text,');
  if (config.refMode === 'no-ref') {
    L.push('      "--no-ref",');
  } else {
    L.push('      "--ref-wav", $RefWav,');
  }
  if (config.caption.trim()) L.push('      "--caption", $Caption,');
  L.push('      "--output-wav", $Wav');
  L.push('    )');
  for (const p of active) {
    const info = FLAG_INFO[p.flag];
    const valExpr = p.type === 'float' ? `$${info.psVar}Str` : `$${info.psVar}`;
    L.push(`    $cmdArgs += @(${psLit('--' + p.flag)}, ${valExpr})`);
  }
  L.push('');
  L.push('    Write-Host "[$Index] $Text"');
  L.push(`    ${config.runPrefix} @cmdArgs`);
  L.push('');

  // Sidecar JSON.
  L.push('    $Meta = [ordered]@{');
  L.push('      schema = "irodori-tts-sidecar/v1"');
  L.push('      wav = "$Name.wav"');
  L.push('      text = $Text');
  L.push('      baseText = $BaseText');
  L.push('      emoji = if ($Emoji -ne "") { $Emoji } else { $null }');
  L.push(`      caption = ${config.caption.trim() ? '$Caption' : '$null'}`);
  L.push('      model = $Model');
  L.push(`      refMode = ${psLit(config.refMode)}`);
  for (const key of ALL_JSON_PARAM_KEYS) {
    const flag = Object.keys(FLAG_INFO).find((f) => FLAG_INFO[f].jsonKey === key)!;
    const isActive = active.some((p) => p.flag === flag);
    L.push(`      ${key} = ${isActive ? '$' + FLAG_INFO[flag].psVar : '$null'}`);
  }
  L.push('      createdAt = (Get-Date).ToUniversalTime().ToString("o")');
  L.push(`      command = "${config.runPrefix} " + ($cmdArgs -join " ")`);
  L.push('    }');
  L.push('    $Meta | ConvertTo-Json -Depth 5 | Set-Content -Path $Json -Encoding UTF8');
  L.push('  }');
  L.push('}');
  L.push('Write-Host "Done. $Index file(s) written to $OutDir"');
  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------------------
// Batch (.bat)
// ---------------------------------------------------------------------------

/** Escape for a cmd `set "VAR=..."` value. */
function batSet(name: string, value: string): string {
  const safe = value.replace(/"/g, '""');
  return `set "${name}=${safe}"`;
}

/** Single-quoted PS literal for bat-embedded one-liners. */
function psLitInline(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** Inline PowerShell (quoted for bat) composing "text|appliedEmoji" from env. */
function batEmojiComposeCmd(config: GenConfig): string {
  const parts: string[] = [
    '$bs=$env:TTS_BASETEXT',
    'function gc($a,$b){$l=[math]::Min($a,$b);$h=[math]::Max($a,$b);Get-Random -Minimum $l -Maximum ($h+1)}',
    "$hd=''",
    "$tl=''",
    "$ap=''",
  ];
  // Head/tail counts per entry.
  for (const e of config.emojiEntries) {
    const tok = psLitInline(e.token);
    const [hMin, hMax] = slot(e, 'head');
    const [tMin, tMax] = slot(e, 'tail');
    parts.push(
      `$h=gc ${hMin} ${hMax}`,
      `$t=gc ${tMin} ${tMax}`,
      `if($h -gt 0){$hd+=(${tok}*$h);$ap+=(${tok}*$h)}`,
      `if($t -gt 0){$tl+=(${tok}*$t);$ap+=(${tok}*$t)}`,
    );
  }
  parts.push('$tx=$hd+$bs+$tl');
  // Random-position inserts per entry.
  for (const e of config.emojiEntries) {
    const tok = psLitInline(e.token);
    const [rMin, rMax] = slot(e, 'rand');
    if (rMax <= 0) continue;
    parts.push(
      `$r=gc ${rMin} ${rMax}`,
      `for($k=0;$k -lt $r;$k++){$pos=Get-Random -Minimum 0 -Maximum ($tx.Length+1);$tx=$tx.Substring(0,$pos)+${tok}+$tx.Substring($pos);$ap+=${tok}}`,
    );
  }
  parts.push("Write-Output ($tx+'|'+$ap)");
  return '"' + parts.join(';') + '"';
}

/**
 * Build a standalone .bat. Integer params use %RANDOM%; float params, emoji
 * composition, and the JSON sidecar are delegated to inline PowerShell (values
 * passed via env vars to avoid cmd quoting/encoding pitfalls with Japanese
 * text + emoji).
 */
export function buildBat(config: GenConfig): string {
  const active = activeParams(config);
  const texts = splitLines(config.texts);
  const checkpointFlag = config.checkpointKind === 'hf' ? '--hf-checkpoint' : '--checkpoint';
  const count = Math.max(1, Math.floor(config.count));
  const useEmoji = emojiEnabled(config);

  const L: string[] = [];
  L.push('@echo off');
  L.push('REM Auto-generated by Irodori-TTS Tools. Random-parameter batch generation.');
  L.push('setlocal enabledelayedexpansion');
  L.push('chcp 65001 > nul');
  L.push('');
  L.push(batSet('OUTDIR', config.outputDir.replace(/\//g, '\\')));
  L.push('if not exist "%OUTDIR%" mkdir "%OUTDIR%"');
  L.push('');
  texts.forEach((t, i) => L.push(batSet(`TEXT[${i}]`, t)));
  L.push(`set /a TEXTCOUNT=${texts.length}`);
  L.push(batSet('MODEL', config.checkpoint));
  if (config.refMode === 'ref-wav') L.push(batSet('REFWAV', config.refWav));
  if (config.caption.trim()) L.push(batSet('CAPTION', config.caption));
  L.push('set /a INDEX=0');
  L.push('');
  L.push('for /L %%T in (0,1,%TEXTCOUNT%) do (');
  L.push('  if %%T lss %TEXTCOUNT% (');
  L.push('    set "BASETEXT=!TEXT[%%T]!"');
  L.push(`    for /L %%I in (1,1,${count}) do (`);
  L.push('      set /a INDEX+=1');
  L.push('      set /a IDXPAD=10000+!INDEX!');
  L.push('      set "IDXSTR=!IDXPAD:~1!"');
  L.push('');

  // Integer params via %RANDOM% (RANDOM is 0..32767; combine for wider range).
  for (const p of active) {
    if (p.type !== 'int') continue;
    const info = FLAG_INFO[p.flag];
    const span = Math.round(p.max) - Math.round(p.min) + 1;
    if (p.kind === 'fixed') {
      L.push(`      set /a ${info.psVar}=${Math.round(p.fixed)}`);
    } else if (span > 32768) {
      L.push(`      set /a ${info.psVar}=(!RANDOM!*32768+!RANDOM!) %% ${span} + ${Math.round(p.min)}`);
    } else {
      L.push(`      set /a ${info.psVar}=!RANDOM! %% ${span} + ${Math.round(p.min)}`);
    }
  }

  // Float params via inline PowerShell.
  for (const p of active) {
    if (p.type !== 'float') continue;
    const info = FLAG_INFO[p.flag];
    if (p.kind === 'fixed') {
      L.push(`      set "${info.psVar}=${p.fixed.toFixed(p.decimals)}"`);
    } else {
      const psExpr = `[math]::Round((${p.min.toFixed(p.decimals)} + (Get-Random -Maximum 10001)/10000 * (${p.max.toFixed(p.decimals)} - ${p.min.toFixed(p.decimals)})),${p.decimals}).ToString([Globalization.CultureInfo]::InvariantCulture)`;
      L.push(
        `      for /f "usebackq delims=" %%v in (\`powershell -NoProfile -Command "${psExpr}"\`) do set "${info.psVar}=%%v"`,
      );
    }
  }

  // Emoji composition (text + applied emoji) via PowerShell.
  L.push('      set "EMOJI="');
  L.push('      set "TTS_TEXT=!BASETEXT!"');
  if (useEmoji) {
    L.push('      set "TTS_BASETEXT=!BASETEXT!"');
    L.push(
      `      for /f "usebackq tokens=1,2 delims=|" %%a in (\`powershell -NoProfile -Command ${batEmojiComposeCmd(config)}\`) do (set "TTS_TEXT=%%a" & set "EMOJI=%%b")`,
    );
  }
  L.push('');

  // Names.
  const hasSeed = active.some((p) => p.flag === 'seed');
  L.push(hasSeed ? '      set "NAME=!IDXSTR!_!Seed!"' : '      set "NAME=!IDXSTR!"');
  L.push('      set "WAV=%OUTDIR%\\!NAME!.wav"');
  L.push('      set "JSON=%OUTDIR%\\!NAME!.json"');
  L.push('');

  // infer.py invocation.
  const inferParts: string[] = [`${config.runPrefix} ${checkpointFlag} "%MODEL%" --text "!TTS_TEXT!"`];
  if (config.refMode === 'no-ref') inferParts.push('--no-ref');
  else inferParts.push('--ref-wav "%REFWAV%"');
  if (config.caption.trim()) inferParts.push('--caption "%CAPTION%"');
  inferParts.push('--output-wav "!WAV!"');
  for (const p of active) {
    inferParts.push(`--${p.flag} !${FLAG_INFO[p.flag].psVar}!`);
  }
  L.push('      echo [!INDEX!] !TTS_TEXT!');
  L.push('      ' + inferParts.join(' '));
  L.push('');

  // Sidecar JSON via PowerShell, reading values from env vars.
  L.push('      set "TTS_BASETEXT=!BASETEXT!"');
  L.push('      set "TTS_EMOJI=!EMOJI!"');
  L.push('      set "TTS_NAME=!NAME!"');
  L.push('      set "TTS_JSON=!JSON!"');
  L.push('      set "TTS_MODEL=%MODEL%"');
  if (config.caption.trim()) L.push('      set "TTS_CAPTION=%CAPTION%"');
  for (const p of active) {
    L.push(`      set "${FLAG_INFO[p.flag].env}=!${FLAG_INFO[p.flag].psVar}!"`);
  }
  L.push('      powershell -NoProfile -Command ' + batJsonPsCommand(config, active));
  L.push('    )');
  L.push('  )');
  L.push(')');
  L.push('echo Done. !INDEX! file(s) written to %OUTDIR%');
  L.push('endlocal');
  L.push('');
  return L.join('\n');
}

/** PowerShell one-liner (quoted for bat) that writes the sidecar JSON from env vars. */
function batJsonPsCommand(config: GenConfig, active: ParamRange[]): string {
  const parts: string[] = [];
  parts.push('$m=[ordered]@{}');
  parts.push("$m.schema='irodori-tts-sidecar/v1'");
  parts.push("$m.wav=$env:TTS_NAME+'.wav'");
  parts.push('$m.text=$env:TTS_TEXT');
  parts.push('$m.baseText=$env:TTS_BASETEXT');
  parts.push('$m.emoji=if($env:TTS_EMOJI){$env:TTS_EMOJI}else{$null}');
  parts.push(config.caption.trim() ? '$m.caption=$env:TTS_CAPTION' : '$m.caption=$null');
  parts.push('$m.model=$env:TTS_MODEL');
  parts.push(`$m.refMode='${config.refMode}'`);
  for (const flag of Object.keys(FLAG_INFO)) {
    const info = FLAG_INFO[flag];
    const p = active.find((a) => a.flag === flag);
    if (!p) {
      parts.push(`$m.${info.jsonKey}=$null`);
    } else if (p.type === 'int') {
      parts.push(`$m.${info.jsonKey}=[int]$env:${info.env}`);
    } else {
      parts.push(`$m.${info.jsonKey}=[double]::Parse($env:${info.env},[Globalization.CultureInfo]::InvariantCulture)`);
    }
  }
  parts.push("$m.createdAt=(Get-Date).ToUniversalTime().ToString('o')");
  parts.push("$m.command=''");
  parts.push('($m|ConvertTo-Json -Depth 5)|Set-Content -Path $env:TTS_JSON -Encoding UTF8');
  return '"' + parts.join(';') + '"';
}
